---
kind: pipeline
type: docker
name: notification

trigger:
  event: [ push, pull_request ]

steps:
  - name: slack before
    image: plugins/slack
    settings:
      channel: drone-ci
      template: >
        {{build.event}} on branch {{build.branch}} from repo {{repo.name}}

        build #{{build.number}} started

        {{build.link}}
      webhook:
        from_secret: SLACK_WEBHOOK_URL

---
kind: pipeline
type: docker
name: build docker images

trigger:
  event: [ push, pull_request ]
  branch:
    exclude:
      - master

steps:
  - name: build images
    image: docker/compose:1.25.5
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f /drone/src/docker-compose.yml -f /drone/src/docker-compose.prod.yml build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind : pipeline
type: docker
name: publish docker images

trigger:
  event: [ push, pull_request ]
  branch:
    exclude:
      - master

steps:
  - name: publish
    image: docker
    environment:
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo $DOCKER_TOKEN | docker login -u gordonpn --password-stdin
      - cd /drone/src/frontend
      - docker build -t gordonpn/speedtest-frontend:latest .
      - docker push gordonpn/speedtest-frontend:latest
      - cd /drone/src/backend
      - docker build -t gordonpn/speedtest-backend:latest .
      - docker push gordonpn/speedtest-backend:latest
      - cd /drone/src/scraper
      - docker build -t gordonpn/speedtest-scraper:latest .
      - docker push gordonpn/speedtest-scraper:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: security

trigger:
  event: [ push, pull_request ]
  branch:
    exclude:
      - master

steps:
  - name: bandit test for scraper
    image: python:3.8-buster
    commands:
      - cd ./scraper
      - pip install bandit
      - bandit -r ./
  - name: safety check for scraper
    image: python:3.8-buster
    commands:
      - cd ./scraper
      - pip install safety
      - safety check
      - safety check -r requirements.txt
  - name: snyk scan
    image: node:14-buster-slim
    environment:
      SNYK_TOKEN:
        from_secret: SNYK_TOKEN
    commands:
      - cd /drone/src/frontend
      - npm install -g snyk
      - snyk test --severity-threshold=high
      - cd /drone/src/backend
      - snyk test --severity-threshold=high

---
kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: deploy prod
    image: docker/compose:1.25.5
    environment:
      COMPOSE_PROJECT_NAME: speedtest
      MONGO_COLLECTION:
        from_secret: MONGO_COLLECTION
      MONGO_INITDB_DATABASE:
        from_secret: MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_PASSWORD:
        from_secret: MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_ROOT_USERNAME:
        from_secret: MONGO_INITDB_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD:
        from_secret: MONGO_NON_ROOT_PASSWORD
      MONGO_NON_ROOT_USERNAME:
        from_secret: MONGO_NON_ROOT_USERNAME
      SCRAPER_HC_UUID:
        from_secret: SCRAPER_HC_UUID
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /bin/sh /drone/src/.docker/scripts/deploy_prod.sh

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: notification after

trigger:
  event: [ push, pull_request ]

steps:
  - name: slack after
    image: plugins/slack
    failure: ignore
    settings:
      channel: drone-ci
      template: >
        {{repo.name}}:
        {{#success build.status}}
        build #{{build.number}} succeeded
        {{else}}
        build #{{build.number}} failed
        {{/success}}
      webhook:
        from_secret: SLACK_WEBHOOK_URL
    when:
      status: [ success, failure ]

depends_on:
  - build docker images
  - publish docker images
  - security
  - deploy
