version: "3.8"
services:

  speedtest-mongodb:
    container_name: speedtest-mongodb
    volumes:
      - mongodb-speedtest:/data/db
    expose:
      - 27017

  speedtest-redis:
    container_name: speedtest-redis
    expose:
      - 6379

  speedtest-scraper:
    container_name: speedtest-scraper

  speedtest-server:
    container_name: speedtest-server
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

  speedtest-client:
    container_name: speedtest-client
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb-speedtest:
    external:
      name: mongodb-speedtest
