version: "3.8"
services:

  mongodb:
    container_name: speedtest-mongodb-dev
    volumes:
      - dev-mongodb-speedtest:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  redis:
    container_name: speedtest-redis-dev
    ports:
      - "127.0.0.1:6379:6379"

  scraper:
    container_name: speedtest-scraper-dev
    environment:
      - DEV_RUN=true

  backend:
    container_name: speedtest-server-dev
    environment:
      - LOG_LEVEL=debug
    ports:
      - "127.0.0.1:3000:3000"

  frontend:
    container_name: speedtest-client-dev
    ports:
      - "127.0.0.1:4000:80"

volumes:
  dev-mongodb-speedtest:
    external:
      name: dev-mongodb-speedtest
