version: "3.8"
services:

  speedtest-mongodb:
    container_name: speedtest-mongodb
    volumes:
      - mongodb-speedtest:/data/db

volumes:
  mongodb-speedtest:
    external:
      name: mongodb-speedtest
