version: "3.8"
services:
  speedtest-scraper:
    container_name: speedtest-scraper
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - SCRAPER_HC_UUID
    depends_on:
      - speedtest-mongodb
  speedtest-mongodb:
    container_name: speedtest-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_ROLE
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
    expose:
      - 27017
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
