version: "3.8"
services:
  mongodb:
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_ROLE=readWrite
      - MONGO_NON_ROOT_USERNAME
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:6-buster
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - MONGO_COLLECTION
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
      - SCRAPER_HC_UUID
      - TZ=America/Montreal
    restart: unless-stopped
    depends_on:
      - mongodb

  backend:
    init: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_COLLECTION
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
      - TZ=America/Montreal
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
      - backend
