version: "3.8"
services:

  speedtest-mongodb:
    container_name: speedtest-mongodb
    volumes:
      - mongodb-speedtest:/data/db
    expose:
      - 27017

  speedtest-redis:
    container_name: speedtest-redis
    expose:
      - 6379

  speedtest-scraper:
    container_name: speedtest-scraper

  speedtest-server:
    container_name: speedtest-server
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  speedtest-client:
    container_name: speedtest-client
    expose:
      - "80"
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1

volumes:
  mongodb-speedtest:
    external:
      name: mongodb-speedtest
