version: "3.8"
services:

  speedtest-mongodb:
    container_name: speedtest-mongodb-dev
    volumes:
      - dev-mongodb-speedtest:/data/db

volumes:
  dev-mongodb-speedtest:
    external:
      name: dev-mongodb-speedtest
