version: "3.8"
services:

  speedtest-mongodb:
    container_name: speedtest-mongodb
    volumes:
      - mongodb-speedtest:/data/db
    expose:
      - 27017

  speedtest-redis:
    container_name: speedtest-redis
    expose:
      - 6379

  speedtest-scraper:
    container_name: speedtest-scraper

  speedtest-server:
    container_name: speedtest-server
    expose:
      - 3000

volumes:
  mongodb-speedtest:
    external:
      name: mongodb-speedtest
